'use strict';
const assert = require('node:assert/strict');
const h = require('./helpers');
module.exports = ({ add, ids }) => {
  const source = ['src/config/cloudinary.js', 'src/features/media/media.controller.js', 'src/features/media/media.routes.js'];
  const reg = (name, actor, method, endpoint, statuses, body, extra = {}) => add(name, actor, method, endpoint, statuses, body, { mode: 'contract', module: 'Offline Cloudinary SDK Contract', sources: source, failureClassification: 'Cloudinary call-contract hardening', ...extra });
  const upload = (name, config, check, extra = {}) => reg(name, 'A', 'POST', '/api/media/upload', [200], undefined, { run: c => h.upload(c, 'A', typeof config === 'function' ? config(c) : config), check, ...extra });
  const lastUpload = c => h.operations(c.sdkState, 'upload_stream').at(-1);
  for (const [context, suffix] of [['message', 'messages'], ['avatar', 'avatars'], ['unknown', 'messages']]) upload(`SDK authenticated ${context} folder`, { context }, (b, c) => { const call = lastUpload(c); return call?.options.folder === `medcollab/${suffix}/${c.users.A._id}` && call.options.resource_type === 'image' && call.sha256 === h.hash(h.png) && b.data.storage === 'cloudinary'; });
  upload('SDK shared handoff has caller ownership namespace', { context: 'handoff' }, (_, c) => lastUpload(c)?.options.folder.includes(String(c.users.A._id)));
  for (const [label, mime, name, bytes, type] of [
    ['PDF', 'application/pdf', 'synthetic.pdf', h.pdf, 'raw'], ['video', 'video/mp4', 'synthetic.mp4', h.video, 'video'],
    ['octet PDF', 'application/octet-stream', 'synthetic.pdf', h.pdf, 'raw'], ['octet video', 'application/octet-stream', 'synthetic.mp4', h.video, 'video'],
  ]) upload(`SDK resource type ${label}`, { mime, name, bytes }, (_, c) => { const call = lastUpload(c); c.evidence.requestedResourceType = call?.options.resource_type; return call?.options.resource_type === type && call.sha256 === h.hash(bytes); });
  upload('SDK filename metadata sanitized and bounded', { name: 'x'.repeat(110) + '<canary>.png' }, (_, c) => { const call = lastUpload(c); return call?.options.filename_override === 'x'.repeat(100) && call.options.use_filename === true && call.options.unique_filename === true && !('public_id' in call.options); });
  upload('SDK explicit overwrite prevention', {}, (_, c) => lastUpload(c)?.options.overwrite === false);
  upload('SDK caller options cannot select identity or transformation', c => ({ fields: { userId: String(c.users.C._id), spaceId: ids.otherSpace, public_id: 'foreign', folder: '../../foreign', resource_type: 'raw', overwrite: 'true', upload_preset: 'untrusted-preset', transformation: 'untrusted' } }), (_, c) => h.same(lastUpload(c)?.options, { folder: `medcollab/messages/${c.users.A._id}`, resource_type: 'image', use_filename: true, unique_filename: true, filename_override: 'synthetic' }));
  upload('SDK image thumbnail exact requested transform', {}, (_, c) => { const call = h.operations(c.sdkState, 'url'); return call.length === 1 && h.same(call[0].options, { width: 400, height: 400, crop: 'limit', quality: 'auto', format: 'webp' }); });
  upload('SDK video thumbnail exact requested transform', { mime: 'video/mp4', name: 'synthetic.mp4', bytes: h.video }, (_, c) => { const call = h.operations(c.sdkState, 'url'); return call.length === 1 && h.same(call[0].options, { resource_type: 'video', format: 'jpg', start_offset: '0', width: 400, crop: 'limit', secure: true }); });
  upload('SDK PDF raw attachment and preview call capture', { mime: 'application/pdf', name: 'synthetic report.pdf', bytes: h.pdf }, (_, c) => { const calls = h.operations(c.sdkState, 'url'); return calls.length === 2 && h.same(calls[0].options, { resource_type: 'raw', flags: 'attachment:synthetic_report.pdf', secure: true }) && h.same(calls[1].options, { resource_type: 'image', format: 'webp', width: 400, height: 300, crop: 'fill', page: 1 }) && calls[0].publicId === calls[1].publicId; });
  upload('SDK PDF preview builder failure is contained', { mime: 'application/pdf', name: 'synthetic.pdf', bytes: h.pdf }, (b, c) => b.data.thumbnailUrl === null && c.sdkState.assets.length === 1, { prepare: c => c.fault('pdf-thumbnail-error') });
  reg('SDK prototype-like context denied before upload', 'A', 'POST', '/api/media/upload', [400], undefined, { run: c => h.upload(c, 'A', { context: 'constructor' }), check: (_, c) => h.operations(c.sdkState, 'upload_stream').length === 0 });
  for (const [label, config, types] of [
    ['image', {}, ['image']], ['raw', { mime: 'application/pdf', name: 'synthetic.pdf', bytes: h.pdf }, ['image', 'raw']], ['video', { mime: 'video/mp4', name: 'synthetic.mp4', bytes: h.video }, ['video']],
  ]) reg(`SDK owner ${label} delete operation`, 'A', 'DELETE', c => '/api/media/' + encodeURIComponent(c.media.publicId), [200], undefined, { prepare: async c => { c.media = await h.own(c, 'A', config); }, check: (_, c) => { const calls = h.operations(c.sdkState, 'destroy'); c.evidence.destroyTypes = calls.map(x => x.options.resource_type); c.evidence.simulatedAssetRetained = c.sdkState.assets.some(a => a.publicId === c.media.publicId); return h.same(c.evidence.destroyTypes, types) && calls.every(x => x.publicId === c.media.publicId) && !c.evidence.simulatedAssetRetained; } });
  reg('SDK deletion requests CDN invalidation', 'A', 'DELETE', c => '/api/media/' + encodeURIComponent(c.media.publicId), [200], undefined, { prepare: async c => { c.media = await h.own(c); }, check: (_, c) => h.operations(c.sdkState, 'destroy').every(call => call.options.invalidate === true) });
  reg('SDK foreign owner rejected without destroy', 'C', 'DELETE', c => '/api/media/' + encodeURIComponent(c.media.publicId), [403], undefined, { prepare: async c => { c.media = await h.own(c); }, check: (_, c) => h.operations(c.sdkState, 'destroy').length === 0 && c.sdkState.assets.some(a => a.publicId === c.media.publicId) });
  reg('SDK delete rejects namespace containing embedded owner', 'A', 'DELETE', c => '/api/media/' + encodeURIComponent(c.attack), [400, 403, 404], undefined, { failureClassification: 'application namespace authorization defect', prepare: async c => { c.media = await h.own(c); c.attack = `foreign-root/messages/${c.users.A._id}/unregistered-canary`; }, check: (_, c) => { c.evidence.destroyDispatches = h.operations(c.sdkState, 'destroy').length; return c.evidence.destroyDispatches === 0; } });
  reg('SDK owner handoff deletion reaches exact asset', 'A', 'DELETE', c => '/api/media/' + encodeURIComponent(c.media.publicId), [200], undefined, { prepare: async c => { c.media = await h.own(c, 'A', { context: 'handoff' }); }, check: (_, c) => h.operations(c.sdkState, 'destroy').length === 1 && !c.sdkState.assets.some(a => a.publicId === c.media.publicId) });
  upload('SDK duplicate original names request unique identity', {}, (_, c) => { const calls = h.operations(c.sdkState, 'upload_stream'); return calls.length === 2 && calls.every(x => x.options.unique_filename === true && !('public_id' in x.options)) && calls[0].options.folder === calls[1].options.folder; }, { prepare: async c => { c.media = await h.own(c); } });
  reg('SDK upload callback failure preserves database', 'A', 'POST', '/api/media/upload', [500], undefined, { prepare: async c => { c.control = await h.own(c); c.evidence.authorizedControl = true; await c.fault('upload-error'); }, run: c => h.upload(c), check: (b, c) => b.message === 'File upload failed. Please try again.' && !JSON.stringify(b).includes('synthetic-sdk-failure') && c.sdkState.assets.length === 1 && c.sdkState.assets[0].publicId === c.control.publicId && h.operations(c.sdkState, 'upload_stream').length === 2 });
  reg('SDK success then URL failure compensates upload', 'A', 'POST', '/api/media/upload', [500], undefined, { prepare: async c => { c.control = await h.own(c); c.evidence.authorizedControl = true; await c.fault('url-error'); }, run: c => h.upload(c), check: (_, c) => { c.evidence.simulatedOrphanCount = c.sdkState.assets.filter(a => a.publicId !== c.control.publicId).length; return c.evidence.simulatedOrphanCount === 0; }, failureClassification: 'partial-failure lifecycle hardening' });
  reg('SDK destroy callback failure preserves asset and reference', 'A', 'DELETE', c => '/api/media/' + encodeURIComponent(c.media.publicId), [500], undefined, { prepare: async c => { c.media = await h.own(c); await h.attach(c, c.media.url); await c.fault('destroy-error'); }, check: async (b, c) => b.message === 'File deletion failed' && !JSON.stringify(b).includes('synthetic-sdk-failure') && c.sdkState.assets.some(a => a.publicId === c.media.publicId) && (await c.models.Handoff.findById(ids.handoff)).patients[0].attachments[0].url === c.media.url });
  reg('SDK uploaded image to authorized message persists reference', 'A', 'POST', `/api/channels/${ids.channel}/messages`, [201], c => ({ type: 'image', content: { mediaUrl: c.media.url, thumbnailUrl: c.media.thumbnailUrl } }), { sources: [...source, 'src/features/messages/message.controller.js:sendMessage'], prepare: async c => { c.media = await h.own(c); }, check: async (b, c) => (await c.models.Message.findById(b.data.message._id)).content.mediaUrl === c.media.url && h.operations(c.sdkState, 'upload_stream').length === 1 });
  reg('SDK video upload to message compatibility', 'A', 'POST', `/api/channels/${ids.channel}/messages`, [201], c => ({ type: 'video', content: { mediaUrl: c.media.url } }), { sources: [...source, 'src/middleware/validate.js:validateSendMessage'], prepare: async c => { c.media = await h.own(c, 'A', { mime: 'video/mp4', name: 'synthetic.mp4', bytes: h.video }); }, check: async (b, c) => !!b.data?.message?._id && (await c.models.Message.findById(b.data.message._id)).content.mediaUrl === c.media.url, failureClassification: 'media compatibility issue' });
  reg('SDK message soft-delete storage lifecycle', 'A', 'DELETE', c => `/api/channels/${ids.channel}/messages/${c.messageId}`, [200], undefined, { prepare: async c => { c.media = await h.own(c); const r = await c.http('A', 'POST', `/api/channels/${ids.channel}/messages`, { type: 'image', content: { mediaUrl: c.media.url } }); assert.equal(r.status, 201); c.messageId = r.data.data.message._id; assert.equal((await c.models.Message.findById(c.messageId)).content.mediaUrl, c.media.url); }, check: async (_, c) => { const doc = await c.models.Message.findById(c.messageId); c.evidence.messageBlanked = doc.isDeleted && doc.content.mediaUrl === null; c.evidence.simulatedAssetRetained = c.sdkState.assets.some(a => a.publicId === c.media.publicId); return c.evidence.messageBlanked && !c.evidence.simulatedAssetRetained; }, failureClassification: 'retention-policy review', sources: [...source, 'src/features/messages/message.controller.js:deleteMessage', 'src/features/messages/message.model.js:pre-save'] });
  reg('SDK avatar replacement call lifecycle characterization', 'A', 'PUT', '/api/users/me', [200], c => ({ avatarUrl: c.second.url }), { prepare: async c => { c.media = await h.own(c, 'A', { context: 'avatar' }); assert.equal((await c.http('A', 'PUT', '/api/users/me', { avatarUrl: c.media.url })).status, 200); c.second = await h.own(c, 'A', { context: 'avatar' }); }, check: async (_, c) => { c.evidence.previousSimulatedAssetRetained = c.sdkState.assets.some(a => a.publicId === c.media.publicId); return (await c.models.User.findById(c.users.A._id)).avatarUrl === c.second.url && h.operations(c.sdkState, 'destroy').length === 0 && c.evidence.previousSimulatedAssetRetained; } });
  reg('SDK foreign-space uploaded reference characterization', 'A', 'POST', `/api/channels/${ids.channel}/messages`, [201], c => ({ type: 'image', content: { mediaUrl: c.foreign.url } }), { prepare: async c => { c.foreign = await h.own(c, 'C'); assert.equal((await c.http('A', 'GET', `/api/channels/${ids.otherChannel}/messages`)).status, 403); }, check: async (b, c) => { const doc = await c.models.Message.findById(b.data.message._id); c.evidence.foreignAssetUrlPersisted = doc.content.mediaUrl === c.foreign.url; return c.evidence.foreignAssetUrlPersisted && h.operations(c.sdkState, 'destroy').length === 0; } });
  reg('SDK empty upload denied before stream invocation', 'A', 'POST', '/api/media/upload', [400], undefined, { run: c => h.upload(c, 'A', { bytes: Buffer.alloc(0) }), check: (_, c) => h.operations(c.sdkState, 'upload_stream').length === 0 });
  reg('SDK oversized upload denied before stream invocation', 'A', 'POST', '/api/media/upload', [400], undefined, { run: c => h.upload(c, 'A', { bytes: Buffer.alloc(25 * 1024 * 1024 + 1) }), check: (_, c) => h.operations(c.sdkState, 'upload_stream').length === 0 });
};
