'use strict';
const assert = require('node:assert/strict'); const fs = require('node:fs'); const path = require('node:path');
const h = require('./helpers');
module.exports = ({ add, ids }) => {
  const source = ['src/features/media/media.routes.js', 'src/features/media/media.controller.js', 'src/utils/localMediaStorage.js'];
  const reg = (name, actor, method, endpoint, statuses, body, extra = {}) => add(name, actor, method, endpoint, statuses, body, { mode: 'local', module: 'Local Media Storage Lifecycle', sources: source, failureClassification: 'validation/hardening issue', ...extra });
  const mp = `/api/channels/${ids.channel}/messages`, hp = `/api/handoffs/${ids.handoff}`;
  for (const [name, actor, header, status] of [['inactive', 'I', null, 401], ['unonboarded', 'U', null, 403], ['expired', 'A', 'expired', 401], ['invalid signature', 'A', 'invalid', 401]]) {
    reg(`upload current identity denial ${name}`, actor, 'POST', '/api/media/upload', [status], undefined, { prepare: async c => { c.control = await h.own(c); c.evidence.authorizedControl = true; }, run: c => h.upload(c, actor, { header: header ? c[header + 'Header'] : undefined }), check: (_, c) => h.files().length === 1 && h.hash(fs.readFileSync(h.file(c.control.publicId))) === h.hash(h.png) });
  }
  reg('duplicate local names preserve independent bytes', 'A', 'POST', '/api/media/upload', [200], undefined, { run: async c => { c.first = await h.own(c); return h.upload(c); }, check: (b, c) => { const second = b.data; c.evidence.independentIds = second.publicId !== c.first.publicId; return c.evidence.independentIds && h.hash(fs.readFileSync(h.file(c.first.publicId))) === h.hash(h.png) && h.hash(fs.readFileSync(h.file(second.publicId))) === h.hash(h.png); } });
  reg('original filename cannot choose local output path', 'A', 'POST', '/api/media/upload', [200], undefined, { run: c => h.upload(c, 'A', { name: '../../foreign/(synthetic).png', fields: { userId: String(c.users.C._id), public_id: '../../foreign', folder: '../../foreign' } }), check: (b, c) => b.data.publicId.startsWith(`medcollab/messages/${c.users.A._id}/`) && path.posix.basename(b.data.publicId).endsWith('.png') && h.files().length === 1 });
  for (const [label, mime, name, bytes] of [['malformed JPEG bytes', 'image/jpeg', 'synthetic.jpg', Buffer.from('inert malformed image')], ['unsupported SVG', 'image/svg+xml', 'synthetic.svg', Buffer.from('inert SVG canary')], ['unsupported MKV', 'video/x-matroska', 'synthetic.mkv', h.video]]) {
    reg(`upload validates ${label}`, 'A', 'POST', '/api/media/upload', [400], undefined, { run: c => h.upload(c, 'A', { mime, name, bytes }), check: () => h.files().length === 0 });
  }
  reg('octet video metadata follows supported extension', 'A', 'POST', '/api/media/upload', [200], undefined, { run: c => h.upload(c, 'A', { mime: 'application/octet-stream', name: 'synthetic.mp4', bytes: h.video }), check: (b, c) => { c.evidence.returnedFormat = b.data?.format; c.evidence.exactBytes = h.hash(fs.readFileSync(h.file(b.data.publicId))) === h.hash(h.video); return b.data.format === 'video' && c.evidence.exactBytes; } });
  for (const actor of ['A', 'C']) reg(`avatar deletion owner boundary ${actor}`, actor, 'DELETE', c => '/api/media/' + encodeURIComponent(c.media.publicId), [actor === 'A' ? 200 : 403], undefined, { prepare: async c => { c.media = await h.own(c, 'A', { context: 'avatar' }); }, check: (_, c) => fs.existsSync(h.file(c.media.publicId)) === (actor !== 'A') });
  reg('avatar canonical foreign owner file survives', 'A', 'DELETE', c => '/api/media/' + encodeURIComponent(c.attack), [400, 403, 404], undefined, { failureClassification: 'confirmed security defect', prepare: async c => { c.media = await h.own(c, 'A', { context: 'avatar' }); c.foreign = await h.own(c, 'C', { context: 'avatar' }); c.attack = `medcollab/avatars/${c.users.A._id}/../${c.users.C._id}/${path.posix.basename(c.foreign.publicId)}`; assert.equal(h.file(c.attack), h.file(c.foreign.publicId)); }, check: (_, c) => { c.evidence.foreignFileSurvived = fs.existsSync(h.file(c.foreign.publicId)); return c.evidence.foreignFileSurvived; } });
  reg('shared handoff upload supports owner deletion', 'A', 'DELETE', c => '/api/media/' + encodeURIComponent(c.media.publicId), [200], undefined, { failureClassification: 'lifecycle/hardening issue', prepare: async c => { c.media = await h.own(c, 'A', { context: 'handoff' }); }, check: (_, c) => { c.evidence.fileSurvived = fs.existsSync(h.file(c.media.publicId)); return !c.evidence.fileSurvived; } });
  reg('avatar replacement retention characterization', 'A', 'PUT', '/api/users/me', [200], c => ({ avatarUrl: c.second.url }), { sources: [...source, 'src/features/users/user.controller.js:updateMe'], prepare: async c => { c.first = await h.own(c, 'A', { context: 'avatar' }); const r = await c.http('A', 'PUT', '/api/users/me', { avatarUrl: c.first.url }); assert.equal(r.status, 200); c.second = await h.own(c, 'A', { context: 'avatar' }); }, check: async (_, c) => { c.evidence.previousFileRetained = fs.existsSync(h.file(c.first.publicId)); c.evidence.newFileRetained = fs.existsSync(h.file(c.second.publicId)); return (await c.models.User.findById(c.users.A._id)).avatarUrl === c.second.url && c.evidence.previousFileRetained && c.evidence.newFileRetained; } });
  reg('foreign uploaded avatar reference characterization', 'A', 'PUT', '/api/users/me', [200], c => ({ avatarUrl: c.foreign.url }), { prepare: async c => { c.foreign = await h.own(c, 'C', { context: 'avatar' }); }, check: async (_, c) => { c.evidence.foreignUrlPersisted = (await c.models.User.findById(c.users.A._id)).avatarUrl === c.foreign.url; return c.evidence.foreignUrlPersisted && h.hash(fs.readFileSync(h.file(c.foreign.publicId))) === h.hash(h.png); } });
  reg('failed profile update retains old reference and upload', 'A', 'PUT', '/api/users/me', [400], c => ({ avatarUrl: c.second.url, role: 'invalid-role' }), { prepare: async c => { c.first = await h.own(c, 'A', { context: 'avatar' }); assert.equal((await c.http('A', 'PUT', '/api/users/me', { avatarUrl: c.first.url })).status, 200); c.second = await h.own(c, 'A', { context: 'avatar' }); }, check: async (_, c) => { c.evidence.unlinkedUploadRetained = fs.existsSync(h.file(c.second.publicId)); return (await c.models.User.findById(c.users.A._id)).avatarUrl === c.first.url && c.evidence.unlinkedUploadRetained; } });
  reg('draft deletion orphan lifecycle', 'A', 'DELETE', hp, [200], undefined, { failureClassification: 'retention-policy review', prepare: async c => { c.media = await h.own(c); await h.attach(c, c.media.url); }, check: async (_, c) => { c.evidence.draftRemoved = !(await c.models.Handoff.findById(ids.handoff)); c.evidence.orphanFileRetained = fs.existsSync(h.file(c.media.publicId)); return c.evidence.draftRemoved && !c.evidence.orphanFileRetained; } });
  reg('explicit file deletion reference consistency', 'A', 'DELETE', c => '/api/media/' + encodeURIComponent(c.media.publicId), [200], undefined, { failureClassification: 'lifecycle-policy review', prepare: async c => { c.media = await h.own(c); await h.attach(c, c.media.url); }, check: async (_, c) => { const doc = await c.models.Handoff.findById(ids.handoff); c.evidence.referenceRetained = doc.patients[0].attachments[0].url === c.media.url; c.evidence.fileRemoved = !fs.existsSync(h.file(c.media.publicId)); return c.evidence.fileRemoved && !c.evidence.referenceRetained; } });
  reg('duplicate references survive forbidden foreign deletion', 'C', 'DELETE', c => '/api/media/' + encodeURIComponent(c.media.publicId), [403], undefined, { prepare: async c => { c.media = await h.own(c); await h.attach(c, c.media.url); const second = await c.models.Handoff.create({ spaceId: ids.space, channelId: ids.channel, fromUserId: c.users.A._id, toUserId: c.users.B._id, shiftDate: '2025-01-15', shiftType: 'morning', patients: h.patient(c.media.url) }); c.secondId = second._id; }, check: async (_, c) => { const docs = await c.models.Handoff.find({ _id: { $in: [ids.handoff, c.secondId] } }); return docs.length === 2 && docs.every(d => d.patients[0].attachments[0].url === c.media.url) && fs.existsSync(h.file(c.media.publicId)); } });
  reg('upload survives rejected foreign destination send', 'A', 'POST', `/api/channels/${ids.otherChannel}/messages`, [403], c => ({ type: 'image', content: { mediaUrl: c.media.url } }), { prepare: async c => { c.media = await h.own(c); }, check: async (_, c) => { c.evidence.unlinkedUploadRetained = fs.existsSync(h.file(c.media.publicId)); return c.evidence.unlinkedUploadRetained && await c.models.Message.countDocuments() === 0; } });
  reg('handoff rejects untrusted attachment URL', 'A', 'PUT', hp, [400], { patients: h.patient('https://example.invalid/inert.pdf') }, { sources: ['src/features/handoffs/handoff.controller.js:updateHandoff', 'src/features/handoffs/handoff.model.js'], prepare: async c => { c.control = await h.own(c); await h.attach(c, c.control.url); c.evidence.authorizedControl = true; }, check: async (_, c) => { const d = await c.models.Handoff.findById(ids.handoff); c.evidence.foreignUrlPersisted = d.patients[0].attachments[0]?.url === 'https://example.invalid/inert.pdf'; return !c.evidence.foreignUrlPersisted; } });
  for (const [name, content] of [
    ['alternate cloud provenance', { mediaUrl: 'https://res.cloudinary.com/alternate-canary/image/upload/inert.png' }],
    ['untrusted thumbnail', { mediaUrl: 'https://res.cloudinary.com/ci-only/image/upload/inert.png', thumbnailUrl: 'https://example.invalid/inert.png' }],
    ['negative size and dimensions', { mediaUrl: 'https://res.cloudinary.com/ci-only/image/upload/inert.png', fileSize: -1, width: -1, height: -1 }],
    ['missing image media URL', { fileName: 'synthetic.png' }],
  ]) reg(`message media validates ${name}`, 'A', 'POST', mp, [400], { type: 'image', content }, { sources: ['src/features/messages/message.controller.js:sendMessage', 'src/features/messages/message.model.js'], prepare: async c => { const r = await c.http('A', 'POST', mp, { type: 'image', content: { mediaUrl: 'https://res.cloudinary.com/ci-only/image/upload/control.png' } }); assert.equal(r.status, 201); const id = r.data.data.message._id; assert.equal((await c.models.Message.findById(id)).content.mediaUrl, 'https://res.cloudinary.com/ci-only/image/upload/control.png'); const read = await c.http('B', 'GET', mp); assert.equal(read.status, 200); assert.ok(read.data.data.messages.some(m => m._id === id)); c.evidence.authorizedControl = true; }, check: async (_, c) => { c.evidence.messagesPersisted = await c.models.Message.countDocuments(); return c.evidence.messagesPersisted === 1; } });
};
